version: "3.8"

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-gemini-bot
    volumes:
      - ./authSession:/app/authSession  # Persist WhatsApp session
    environment:
      - GEMINI_API_KEY=AIzaSyAAmtWEYrRJ4ainiC_mAw4PENOcst2YhSA  # Use your .env file
      - DOCKER_CONTAINER=true  # Signal to use Docker-specific paths
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium  # Explicitly set the path
    env_file:
      - .env
    restart: unless-stopped  # Changed from "no" to restart automatically if it crashes